#!/usr/bin/env bash

#Check for template file
if [ -z "$1" ]; then
    echo "A template is needed"
    exit 1
fi
TEMPLATE=$1

#Check for stack name
if [ -z "$2" ]; then
    echo "A stack name is needed"
    exit 1
fi
STACK_NAME=$2


#Deploy cloudformation template using aws cli
aws cloudformation deploy \
--template-file $TEMPLATE \
--capabilities CAPABILITY_NAMED_IAM \
--no-execute-changeset \
--stack-name $STACK_NAME