#!/usr/bin/env bash


# Exit immediately if any command returns an error
set -e

#Check for bucket name
if [ -z "$1" ]; then
    echo "VPC ID is required"
    exit 1
fi
VPC_ID=$1

#Delete vpc
aws ec2 delete-vpc --vpc-id $VPC_ID