#!/usr/bin/env bash

#Check for bucket name
if [ -z "$1" ]; then
    echo "A bucket name is need"
    exit 1
fi
BUCKET_NAME=$1

# Check if the bucket already exists
if aws s3api head-bucket --bucket "$BUCKET_NAME" 2>/dev/null; then
    echo "Bucket $BUCKET_NAME already exists."
else
    # Create the bucket if it does not exist
    aws s3api create-bucket --bucket "$BUCKET_NAME" --query Location --output text
    if [ $? -eq 0 ]; then
        echo "Bucket $BUCKET_NAME created successfully"
    else
        echo "Failed to create bucket $BUCKET_NAME."
        exit 3
    fi
fi