#!/usr/bin/env bash

#Check for bucket name
if [ -z "$1" ]; then
    echo "A bucket name is needed"
    exit 1
fi
BUCKET_NAME=$1

# Check if the bucket NOT exists
if ! aws s3api head-bucket --bucket "$BUCKET_NAME" 2>/dev/null; then
    echo "Bucket $BUCKET_NAME NOT exists."
else
    aws s3api delete-bucket --bucket $BUCKET_NAME

    if [ $? -eq 0 ]; then
        echo "Bucket $BUCKET_NAME deleted successfully"
    else
        echo "Failed to create bucket $BUCKET_NAME."
        exit 3
    fi
fi